const basePath = '../assets/images'
export const logos = {
    IP: require(`${basePath}/IP.png`),
    mrnew: require(`${basePath}/mrnew.png`),
    MYJOB:  require(`${basePath}/MYJOB.png`),
    odo: require(`${basePath}/odo.png`),
    utkalbottling:  require(`${basePath}/utkalbottling.png`),
    utkalcorporation:  require(`${basePath}/utkalcorporation.png`),
    utkaleducation: require(`${basePath}/utkaleducation.png`),
    utkalfacility:  require(`${basePath}/utkalfacility.png`),
    utkalfoundation: require(`${basePath}/utkalfoundation.png`),
    utkalglobal: require(`${basePath}/utkalglobal.png`),
    utkalhome: require(`${basePath}/utkalhome.png`),
    utkalinternational: require(`${basePath}/utkalinternational.png`),
    utkalone: require(`${basePath}/utkalone.png`),
    utkalpower:  require(`${basePath}/utkalpower.png`),
    utkalsmart: require(`${basePath}/utkalsmart.png`),
    ZSecurity:   require(`${basePath}/ZSecurity.png`),
    Ayushman: require(`${basePath}/Ayushman.png`),
    Topfront:  require(`${basePath}/Topfront.png`),
    maxim:  require(`${basePath}/maxim.png`),
    Homedeal: require(`${basePath}/Homedeal.png`),
    ibis: require(`${basePath}/ibis.png`),
    logo: require(`${basePath}/logo.png`),
}; 